[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-gnu:edge"

[target.loongarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-musl:edge"

[target.x86_64-unknown-netbsd]
dockerfile = "./docker/Dockerfile.x86_64-unknown-netbsd"
